export const CREATE_DISCOUNT_REQUEST = 'CREATE_DISCOUNT_REQUEST';
export const CREATE_DISCOUNT_SUCCESS = 'CREATE_DISCOUNT_SUCCESS';
export const CREATE_DISCOUNT_FAIL = 'CREATE_DISCOUNT_FAIL';
export const CREATE_DISCOUNT_RESET = 'CREATE_DISCOUNT_RESET';

export const GET_DISCOUNT_REQUEST = 'GET_DISCOUNT_REQUEST';
export const GET_DISCOUNT_SUCCESS = 'GET_DISCOUNT_SUCCESS';
export const GET_DISCOUNT_FAIL = 'GET_DISCOUNT_FAIL';

export const UPDATE_DISCOUNT_REQUEST = 'UPDATE_DISCOUNT_REQUEST';
export const UPDATE_DISCOUNT_SUCCESS = 'UPDATE_DISCOUNT_SUCCESS';
export const UPDATE_DISCOUNT_FAIL = 'UPDATE_DISCOUNT_FAIL';
export const UPDATE_DISCOUNT_RESET = 'UPDATE_DISCOUNT_RESET';

export const DELETE_DISCOUNT_REQUEST = 'DELETE_DISCOUNT_REQUEST';
export const DELETE_DISCOUNT_SUCCESS = 'DELETE_DISCOUNT_SUCCESS';
export const DELETE_DISCOUNT_FAIL = 'DELETE_DISCOUNT_FAIL';
export const DELETE_DISCOUNT_RESET = 'DELETE_DISCOUNT_RESET';

export const VERIFI_DISCOUNT_REQUEST = 'VERIFI_DISCOUNT_REQUEST';
export const VERIFI_DISCOUNT_SUCCESS = 'VERIFI_DISCOUNT_SUCCESS';
export const VERIFI_DISCOUNT_FAIL = 'VERIFI_DISCOUNT_FAIL';
export const VERIFI_DISCOUNT_RESET = 'VERIFI_DISCOUNT_RESET';
