export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

export const ORDER_LIST_COMPLETE_REQUEST = 'ORDER_LIST_COMPLETE_REQUEST';
export const ORDER_LIST_COMPLETE_SUCCESS = 'ORDER_LIST_COMPLETE_SUCCESS';
export const ORDER_LIST_COMPLETE_FAIL = 'ORDER_LIST_COMPLETE_FAIL';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const ORDER_DELIVERED_REQUEST = 'ORDER_DELIVERED_REQUEST';
export const ORDER_DELIVERED_SUCCESS = 'ORDER_DELIVERED_SUCCESS';
export const ORDER_DELIVERED_FAIL = 'ORDER_DELIVERED_FAIL';
export const ORDER_DELIVERED_RESET = 'ORDER_DELIVERED_RESET';

export const ORDER_PAID_REQUEST = 'ORDER_PAID_REQUEST';
export const ORDER_PAID_SUCCESS = 'ORDER_PAID_SUCCESS';
export const ORDER_PAID_FAIL = 'ORDER_PAID_FAIL';
export const ORDER_PAID_RESET = 'ORDER_PAID_RESET';

export const ORDER_CANCEL_REQUEST = 'ORDER_CANCEL_REQUEST';
export const ORDER_CANCEL_SUCCESS = 'ORDER_CANCEL_SUCCESS';
export const ORDER_CANCEL_FAIL = 'ORDER_CANCEL_FAIL';
export const ORDER_CANCEL_RESET = 'ORDER_CANCEL_RESET';

export const ORDER_WAITCONFIRMATION_REQUEST = 'ORDER_WAITCONFIRMATION_REQUEST';
export const ORDER_WAITCONFIRMATION_SUCCESS = 'ORDER_WAITCONFIRMATION_SUCCESS';
export const ORDER_WAITCONFIRMATION_FAIL = 'ORDER_WAITCONFIRMATION_FAIL';
export const ORDER_WAITCONFIRMATION_RESET = 'ORDER_WAITCONFIRMATION_RESET';

export const ORDER_COMPLETE_ADMIN_REQUEST = 'ORDER_COMPLETE_ADMIN_REQUEST';
export const ORDER_COMPLETE_ADMIN_SUCCESS = 'ORDER_COMPLETE_ADMIN_SUCCESS';
export const ORDER_COMPLETE_ADMIN_FAIL = 'ORDER_COMPLETE_ADMIN_FAIL';
export const ORDER_COMPLETE_ADMIN_RESET = 'ORDER_COMPLETE_ADMIN_RESET';

export const ORDER_ERROR_PAID_REQUEST = 'ORDER_ERROR_PAID_REQUEST';
export const ORDER_ERROR_PAID_SUCCESS = 'ORDER_ERROR_PAID_SUCCESS';
export const ORDER_ERROR_PAID_FAIL = 'ORDER_ERROR_PAID_FAIL';
export const ORDER_ERROR_PAID_RESET = 'ORDER_ERROR_PAID_RESET';

export const ORDER_ERROR_PAID_CONTENT_REQUEST = 'ORDER_ERROR_PAID_CONTENT_REQUEST';
export const ORDER_ERROR_PAID_CONTENT_SUCCESS = 'ORDER_ERROR_PAID_CONTENT_SUCCESS';
export const ORDER_ERROR_PAID_CONTENT_FAIL = 'ORDER_ERROR_PAID_CONTENT_FAIL';
export const ORDER_ERROR_PAID_CONTENT_RESET = 'ORDER_ERROR_PAID_CONTENT_RESET';

export const ORDER_NOTE_GUAREEN_REQUEST = 'ORDER_NOTE_GUAREEN_REQUEST';
export const ORDER_NOTE_GUAREEN_SUCCESS = 'ORDER_NOTE_GUAREEN_SUCCESS';
export const ORDER_NOTE_GUAREEN_FAIL = 'ORDER_NOTE_GUAREEN_FAIL';
export const ORDER_NOTE_GUAREEN_RESET = 'ORDER_NOTE_GUAREEN_RESET';

export const ORDER_GUARANTEE_REQUEST = 'ORDER_GUARANTEE_REQUEST';
export const ORDER_GUARANTEE_SUCCESS = 'ORDER_GUARANTEE_SUCCESS';
export const ORDER_GUARANTEE_FAIL = 'ORDER_GUARANTEE_FAIL';
export const ORDER_GUARANTEE_RESET = 'ORDER_GUARANTEE_RESET';

export const PRINT_ORDER_REQUEST = 'PRINT_ORDER_REQUEST';
export const PRINT_ORDER_SUCCESS = 'PRINT_ORDER_SUCCESS';
export const PRINT_ORDER_FAIL = 'PRINT_ORDER_FAIL';
export const PRINT_ORDER_RESET = 'PRINT_ORDER_RESET';
