export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';
export const USER_LIST_RESET = 'USER_LIST_RESET';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const USER_DISABLED_REQUEST = 'USER_DISABLED_REQUEST';
export const USER_DISABLED_SUCCESS = 'USER_DISABLED_SUCCESS';
export const USER_DISABLED_FAIL = 'USER_DISABLED_FAIL';
export const USER_DISABLED_RESET = 'USER_DISABLED_RESET';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
export const CREATE_USER_RESET = 'CREATE_USER_RESET';

export const CREATE_IMAGE_USER_REQUEST = 'CREATE_IMAGE_USER_REQUEST';
export const CREATE_IMAGE_USER_SUCCESS = 'CREATE_IMAGE_USER_SUCCESS';
export const CREATE_IMAGE_USER_FAIL = 'CREATE_IMAGE_USER_FAIL';
export const CREATE_IMAGE_USER_RESET = 'CREATE_IMAGE_USER_RESET';

export const SEND_EMAIL_USER_REQUEST = 'SEND_EMAIL_USER_REQUEST';
export const SEND_EMAIL_USER_SUCCESS = 'SEND_EMAIL_USER_SUCCESS';
export const SEND_EMAIL_USER_FAIL = 'SEND_EMAIL_USER_FAIL';
export const SEND_EMAIL_USER_RESET = 'SEND_EMAIL_USER_RESET';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const UPDATE_USER_RESET = 'UPDATE_USER_RESET';

export const ADD_GIFT_REQUEST = 'ADD_GIFT_REQUEST';
export const ADD_GIFT_SUCCESS = 'ADD_GIFT_SUCCESS';
export const ADD_GIFT_FAIL = 'ADD_GIFT_FAIL';
export const ADD_GIFT_RESET = 'ADD_GIFT_RESET';
