export const CHECK_DISCOUNT_REQUEST = 'CHECK_DISCOUNT_REQUEST';
export const CHECK_DISCOUNT_SUCCESS = 'CHECK_DISCOUNT_SUCCESS';
export const CHECK_DISCOUNT_FAIL = 'CHECK_DISCOUNT_FAIL';
export const CHECK_DISCOUNT_RESET = 'CHECK_DISCOUNT_RESET';
