export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';
export const USER_UPDATE_PASSWORD_SUCCESS = 'USER_UPDATE_PASSWORD_SUCCESS';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';
export const USER_LIST_RESET = 'USER_LIST_RESET';

export const CREACTE_USER_REQUEST = 'CREACTE_USER_REQUEST';
export const CREACTE_USER_SUCCESS = 'CREACTE_USER_SUCCESS';
export const CREACTE_USER_FAIL = 'CREACTE_USER_FAIL';
export const CREACTE_USER_RESET = 'CREACTE_USER_RESET';

export const GET_GIFT_REQUEST = 'GET_GIFT_REQUEST';
export const GET_GIFT_SUCCESS = 'GET_GIFT_SUCCESS';
export const GET_GIFT_FAIL = 'GET_GIFT_FAIL';

export const ADD_GIFT_REQUEST = 'ADD_GIFT_REQUEST';
export const ADD_GIFT_SUCCESS = 'ADD_GIFT_SUCCESS';
export const ADD_GIFT_FAIL = 'ADD_GIFT_FAIL';
export const ADD_GIFT_RESET = 'ADD_GIFT_RESET';
